#include <stdio.h>
#include <string.h>
#include "graphplan.h"
#include "dump_search.h"

static FILE *tf = NULL;
static int  step_n = 0;
static int  first_event = 1;

/* ── helpers ─────────────────────────────────────────────── */
static void sep(void) {
    if (!first_event) fputs(",\n", tf);
    first_event = 0;
}

static void prop_id(int t, const char *name) {
    fprintf(tf, "\"prop_%d_%s\"", t, name);
}
static void act_id(int t, const char *name) {
    fprintf(tf, "\"act_%d_%s\"", t, name);
}

/* ── lifecycle ───────────────────────────────────────────── */
void trace_open(void) {
    tf = fopen("search_trace.js", "w");
    if (!tf) { perror("trace_open"); return; }
    fputs("/* Auto-generated by Graphplan – do not edit */\n", tf);
    fputs("const SEARCH_TRACE = [\n", tf);
    step_n = 0; first_event = 1;
}

void trace_close(void) {
    if (!tf) return;
    fputs("\n];\n", tf);
    fclose(tf); tf = NULL;
    puts("Search trace written to search_trace.js");
}

/* ── events ──────────────────────────────────────────────── */

/* Emitted when basicplan transitions to a new time layer */
void trace_goal_set(int time, goal_arr goals, int n) {
    if (!tf) return;
    int i; sep();
    fprintf(tf, "  {\"step\":%d,\"type\":\"goal_set\",\"time\":%d,\"goals\":[",
            step_n++, time);
    for (i = 0; i < n; i++) {
        if (i) fputs(",", tf);
        prop_id(time, goals[i]->name);
    }
    fputs("]}", tf);
}

/* Emitted when we're about to try an action for a goal */
void trace_try(int time, vertex_t op, vertex_t for_goal) {
    if (!tf) return;
    sep();
    /* time here is the action layer = time-1 in basicplan's frame */
    fprintf(tf, "  {\"step\":%d,\"type\":\"try\",\"time\":%d,\"action\":",
            step_n++, time);
    act_id(time, op->name);
    fputs(",\"for_goal\":", tf);
    prop_id(time + 1, for_goal->name);   /* goal is at time+1 layer */
    fputs("}", tf);
}

/* Action skipped — mutex with an already-chosen action */
void trace_mutex(int time, vertex_t op, vertex_t for_goal) {
    if (!tf) return;
    sep();
    fprintf(tf, "  {\"step\":%d,\"type\":\"mutex\",\"time\":%d,\"action\":",
            step_n++, time);
    act_id(time, op->name);
    fputs(",\"for_goal\":", tf);
    prop_id(time + 1, for_goal->name);
    fputs("}", tf);
}

/* Action abandoned — would make a remaining goal unreachable */
void trace_cutoff(int time, vertex_t op, vertex_t for_goal) {
    if (!tf) return;
    sep();
    fprintf(tf, "  {\"step\":%d,\"type\":\"cutoff\",\"time\":%d,\"action\":",
            step_n++, time);
    act_id(time, op->name);
    fputs(",\"for_goal\":", tf);
    prop_id(time + 1, for_goal->name);
    fputs("}", tf);
}

/* Action committed to */
void trace_select(int time, vertex_t op) {
    if (!tf) return;
    sep();
    fprintf(tf, "  {\"step\":%d,\"type\":\"select\",\"time\":%d,\"action\":",
            step_n++, time);
    act_id(time, op->name);
    fputs("}", tf);
}

/* Action uncommitted (undo on backtrack) */
void trace_deselect(int time, vertex_t op) {
    if (!tf) return;
    sep();
    fprintf(tf, "  {\"step\":%d,\"type\":\"deselect\",\"time\":%d,\"action\":",
            step_n++, time);
    act_id(time, op->name);
    fputs("}", tf);
}

/* No action set worked at this layer */
void trace_backtrack(int time) {
    if (!tf) return;
    sep();
    fprintf(tf, "  {\"step\":%d,\"type\":\"backtrack\",\"time\":%d}", step_n++, time);
}

/* Plan found — emit which actions ended up used */
void trace_solution(int maxtime) {
    if (!tf) return;
    extern hashtable_t *op_table;
    int t;
    vertex_t v;
    int first_layer = 1; // Tracks if we need a comma between layer blocks

    sep();
    fprintf(tf, "  {\"step\":%d,\"type\":\"solution\",\"plan\":{", step_n++);

    for (t = 0; t < maxtime; t++) {
        int first_action_in_layer = 1;

        get_next(op_table[t], 0);
        while ((v = get_next(op_table[t], 1)) != NULL) {
            if (!v->used || v->is_noop) continue;

            // If this is the very first action we found for this time layer
            if (first_action_in_layer) {
                // Do we need a comma between "1":[...] and "2":[...]?
                if (!first_layer) fputs(",", tf);

                fprintf(tf, "\"%d\":[", t + 1);
                first_action_in_layer = 0;
                first_layer = 0;
            } else {
                // Standard comma between actions in the same list
                fputs(",", tf);
            }

            fprintf(tf, "\"%s\"", v->name);
        }

        // Close the array only if we actually started one for this layer
        if (!first_action_in_layer) {
            fputs("]", tf);
        }
    }
    fputs("}}", tf);
}

void trace_failure(void) {
    if (!tf) return;
    sep();
    fprintf(tf, "  {\"step\":%d,\"type\":\"failure\"}", step_n++);
}