/*********************** Graphplan Visualizer ****************************
 * dump_json.c
 *
 * Serialises the fully-built planning graph into graph_data.js so the
 * D3 web visualizer can load it without a server.
 *************************************************************************/

#include <stdio.h>
#include <string.h>
#include "graphplan.h"
#include "dump_json.h"

/* Globals defined in graphplan.c */
extern hashtable_t *fact_table, *op_table;
extern fact_list    the_goals;

/* ── helpers ──────────────────────────────────────────────────────────── */

/* Write a C string as a JSON-safe string (no surrounding quotes). */
static void esc(FILE *f, const char *s)
{
    for (; *s; ++s) {
        switch (*s) {
            case '"':  fputs("\\\"", f); break;
            case '\\': fputs("\\\\", f); break;
            case '\n': fputs("\\n",  f); break;
            case '\r': fputs("\\r",  f); break;
            default:   fputc(*s, f);
        }
    }
}

/* Emit a proposition-node id: "prop_{time}_{name}" */
static void prop_id(FILE *f, int t, const char *name)
{
    fprintf(f, "prop_%d_", t);
    esc(f, name);
}

/* Emit an action-node id: "act_{time}_{name}" */
static void act_id(FILE *f, int t, const char *name)
{
    fprintf(f, "act_%d_", t);
    esc(f, name);
}

/* Comma management: print ", " before every item except the first. */
static void sep(FILE *f, int *first)
{
    if (!*first) fputs(",\n", f);
    *first = 0;
}

/* ── main export ──────────────────────────────────────────────────────── */

void dump_graph_js(int maxtime)
{
    FILE *f = fopen("graph_data.js", "w");
    if (!f) { perror("dump_graph_js: cannot open graph_data.js"); return; }

    vertex_t   v;
    edgelist_t e;
    fact_list  gl;
    char       str[512];
    int        first;
    int        t;

    fputs("/* Auto-generated by Graphplan – do not edit by hand */\n", f);
    fputs("const GRAPH_DATA = {\n", f);

    /* ================================================================
     * NODES
     * Proposition nodes: prop_{t}_{name}  col = t*2
     * Action nodes:      act_{t}_{name}   col = t*2+1
     * ================================================================ */
    fputs("  nodes: [\n", f);
    first = 1;

    for (t = 0; t <= maxtime; t++) {

        /* Proposition nodes at time t */
        get_next(fact_table[t], 0);
        while ((v = get_next(fact_table[t], 1)) != NULL) {
            sep(f, &first);
            fputs("    { id:\"", f); prop_id(f, t, v->name);
            fputs("\", label:\"", f); esc(f, v->name);
            fprintf(f, "\", kind:\"prop\", time:%d, col:%d }", t, t * 2);
        }

        /* Action nodes at time t (no action level after final prop level) */
        if (t < maxtime) {
            get_next(op_table[t], 0);
            while ((v = get_next(op_table[t], 1)) != NULL) {
                sep(f, &first);
                fputs("    { id:\"", f); act_id(f, t, v->name);
                fputs("\", label:\"", f); esc(f, v->name);
                fprintf(f, "\", kind:\"%s\", time:%d, col:%d }",
                        v->is_noop ? "noop" : "action", t, t * 2 + 1);
            }
        }
    }
    fputs("\n  ],\n\n", f);

    /* ================================================================
     * EDGES
     * pre  – proposition(t) → action(t)        (precondition)
     * add  – action(t)      → proposition(t+1) (add effect)
     * del  – action(t)      → proposition(t+1) (delete effect)
     * ================================================================ */
    fputs("  edges: [\n", f);
    first = 1;

    for (t = 0; t < maxtime; t++) {
        get_next(op_table[t], 0);
        while ((v = get_next(op_table[t], 1)) != NULL) {

            /* precondition edges */
            for (e = v->in_edges; e; e = e->next) {
                sep(f, &first);
                fputs("    { src:\"", f); prop_id(f, t,   e->endpt->name);
                fputs("\", tgt:\"",   f); act_id (f, t,   v->name);
                fputs("\", etype:\"pre\" }", f);
            }

            /* add-effect edges */
            for (e = v->out_edges; e; e = e->next) {
                sep(f, &first);
                fputs("    { src:\"", f); act_id (f, t,   v->name);
                fputs("\", tgt:\"",   f); prop_id(f, t+1, e->endpt->name);
                fputs("\", etype:\"add\" }", f);
            }

            /* delete-effect edges
             * del_edges is populated by find_mutex_ops; each endpoint is
             * a fact node in fact_table[t+1].                            */
            for (e = v->del_edges; e; e = e->next) {
                sep(f, &first);
                fputs("    { src:\"", f); act_id (f, t,   v->name);
                fputs("\", tgt:\"",   f); prop_id(f, t+1, e->endpt->name);
                fputs("\", etype:\"del\" }", f);
            }
        }
    }
    fputs("\n  ],\n\n", f);

    /* ================================================================
     * MUTEX PAIRS – actions
     * Only emit each pair once (compare names to avoid duplicates).
     * ================================================================ */
    fputs("  mutexActions: [\n", f);
    first = 1;

    for (t = 0; t < maxtime; t++) {
        get_next(op_table[t], 0);
        while ((v = get_next(op_table[t], 1)) != NULL) {
            for (e = v->exclusive; e; e = e->next) {
                /* emit only when v->name < partner->name lexicographically */
                if (strcmp(v->name, e->endpt->name) >= 0) continue;
                sep(f, &first);
                fputs("    [\"", f); act_id(f, t, v->name);
                fputs("\",\"",   f); act_id(f, t, e->endpt->name);
                fputs("\"]", f);
            }
        }
    }
    fputs("\n  ],\n\n", f);

    /* ================================================================
     * MUTEX PAIRS – propositions
     * ================================================================ */
    fputs("  mutexProps: [\n", f);
    first = 1;

    for (t = 1; t <= maxtime; t++) {
        get_next(fact_table[t], 0);
        while ((v = get_next(fact_table[t], 1)) != NULL) {
            for (e = v->exclusive; e; e = e->next) {
                if (strcmp(v->name, e->endpt->name) >= 0) continue;
                sep(f, &first);
                fputs("    [\"", f); prop_id(f, t, v->name);
                fputs("\",\"",   f); prop_id(f, t, e->endpt->name);
                fputs("\"]", f);
            }
        }
    }
    fputs("\n  ],\n\n", f);

    /* ================================================================
     * GOALS
     * ================================================================ */
    fputs("  goals: [", f);
    first = 1;
    for (gl = the_goals; gl; gl = gl->next) {
        instantiate_into_string(gl->item, NULL, str, 1);
        if (!first) fputs(", ", f);
        first = 0;
        fputs("\"", f); prop_id(f, maxtime, str); fputs("\"", f);
    }
    fputs("],\n\n", f);

    /* ================================================================
     * METADATA
     * ================================================================ */
    fprintf(f, "  maxtime: %d\n};\n", maxtime);

    fclose(f);
    puts("Visualizer data written to graph_data.js");
}
